### ISSUE TITLE
CIS-AwsSupportRoleExists Config rule doesn't quite capture the compliance requirements

### ISSUE THREAD

**Issue by doshitan** [aws-quickstart/quickstart-enterprise-accelerator-cis-benchmark#2]
The check for 1.22 only states that the `AWSSupportAccess` policy is attached to *something*, it does not need to be attached to a group, role *and* a user, just at least one of them.  If the policy is attached to one of the types, maybe the check could return `NOT_APPLICABLE` instead of `NON_COMPLIANT` for the other types.

**Comment by aravindkaws** [comment]
Thanks for feedback. This change has been implemented and the Security Controls Matrix has been updated with guidance on the behavior when none of the IAM Entities have the policy assigned.
