### ISSUE TITLE
Lambda function - CIS 2.2 & 2.7

### ISSUE THREAD

**Issue by gowthamsubbu** [aws-quickstart/quickstart-enterprise-accelerator-cis-benchmark#3]
For CIS AWS Foundations Benchmark - 2.2   Ensure CloudTrail log file validation is enabled and CIS AWS Foundations Benchmark - 2.7   Ensure CloudTrail logs are encrypted at rest using KMS CMKs 

Issue:
If there are more than one Cloudtrail and if the first trail in the loop is Non-Compliant then the following trails which are compliant are reported as Non-Compliant. 

In the lambda function is_compliant = True is set above the for loop and as a result is_compliant is not getting reset while evaluating subsequent trails and carrying the value of previous trail.

 is_compliant = True should be declared as below

for trail in client_ct.describe_trails()['trailList']:
     is_compliant = True
    if trail['HomeRegion'] == context.invoked_function_arn.split(':')[3]:

**Comment by aravindkaws** [comment]
Thanks for catching this Gowtham. This has been fixed !!
