### ISSUE TITLE
Lambda Function CIS 1.12  - 1.14

### ISSUE THREAD

**Issue by jonesmcbones** [aws-quickstart/quickstart-enterprise-accelerator-cis-benchmark#4]
Hi

The Config rule "CIS-RootAccoutMustHaveMfaEnabled" is reporting "no results available" despite the root account being compliant on all three items.

I raised a service ticket with AWS Support who have established that it is a problem in the Lambda function's code but advised I raise the issue here as they cannot assist with Quick Starts.

**Comment by aravindkaws** [comment]
Hi,
Have you verified if the backing Lambda function is executing successfully and that there are no errors thrown?

**Comment by jonesmcbones** [comment]
I apologise, this was present in Cloudwatch.

An error occurred (ValidationException) when calling the PutEvaluations operation: 1 validation error detected: Value ' The root account has MFA enabled. The root account does NOT have hardware-based MFA enabled. The root account does NOT have hardware-based MFA enabled. The root account does NOT have hardware-based MFA enabled. The root account does NOT have hardware-based MFA enabled. The root account does NOT have active access keys associated with it.' at 'evaluations.1.member.annotation' failed to satisfy constraint: Member must have length less than or equal to 256: ValidationException
Traceback (most recent call last):
File "/var/task/index.py", line 67, in lambda_handler
ResultToken=result_token
File "/var/runtime/botocore/client.py", line 317, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 615, in _make_api_call
raise error_class(parsed_response, operation_name)
ValidationException: An error occurred (ValidationException) when calling the PutEvaluations operation: 1 validation error detected: Value ' The root account has MFA enabled. The root account does NOT have hardware-based MFA enabled. The root account does NOT have hardware-based MFA enabled. The root account does NOT have hardware-based MFA enabled. The root account does NOT have hardware-based MFA enabled. The root account does NOT have active access keys associated with it.' at 'evaluations.1.member.annotation' failed to satisfy constraint: Member must have length less than or equal to 256

**Comment by aravindkaws** [comment]
Thanks Jones. This issue should be fixed.

**Comment by aravindkaws** [comment]
Fixed the annotation initialization problem.
