### ISSUE TITLE
CloudWatch alarms need better comparisons and/or thresholds

### ISSUE THREAD

**Issue by doshitan** [aws-quickstart/quickstart-enterprise-accelerator-cis-benchmark#7]
Generally they should be using `GreaterThanOrEqualToThreshold` for the comparisons so that they actually trigger for single events (like a root login or when a KMS key gets disabled). Or the thresholds could be set to `0` instead of `1` I suppose.

Also, `CIS-Unauthorized Activity Attempt` and `CIS-Console Login Failures` both have higher thresholds than recommend in the benchmarks.

**Comment by aravindkaws** [comment]
This has been fixed.
